// svelte-viewer/src/App.svelte
<script lang="ts">
  import Viewer from "./Viewer.svelte";

  const person = {
    name: "Steveo",
    age: 27,
    todo: [
      { task: "Do this", priority: 2 },
      { task: "Do this", priority: 1 },
      { task: "Do this", priority: 4 },
    ],
  };
</script>

<h2>Simple Types</h2>
<Viewer value={1} />
<Viewer value={'Hello'} />
<Viewer value={'false'} />

<h2>Object</h2>
<Viewer value={person} />

// react-viewer/src/App.tsx
import React from 'react';
import { Container, Row, Col } from 'react-bootstrap';
import './App.css';
import { Viewer } from './Viewer';

const person = {
  name: "Steveo",
  age: 27,
  todo: [
    { task: "Do this", priority: 2 },
    { task: "Do this", priority: 1 },
    { task: "Do this", priority: 5 },
  ],
};

function App() {
  return (
    <Container>
      <Row>
        <Col>
          <Viewer value={person}></Viewer>
        </Col>
      </Row>
    </Container>
  );
}

export default App;
