// svelte-viewer/src/Viewer.svelte
<script lang="ts">
import { getRenderType, getKeyValues } from "./meta.svelte";
import { Table } from 'sveltestrap';


  //   import { getRenderType } from "meta";

  export let value: unknown;

  $: info = getRenderType(value);


</script>

<!-- <div>{info.type}</div> -->
{#if info.type === 'simple-value'}
  <div>{info.value}</div>
{:else if info.type === 'object'}
  <Table bordered striped size="sm">
    {#each getKeyValues(info.value) as { key, value }, i}
      <tr>
        <th>{key}</th>
        <td>
          <svelte:self {value} />
        </td>
      </tr>
    {/each}
  </Table>
{:else if info.type === 'array'}
  <Table bordered striped size="sm">
    {#if info.keys}
      <thead>
        <tr>
          {#each info.keys as key}
            <th>{key}</th>
          {/each}
        </tr>
      </thead>
    {/if}

    <tbody>
      {#if info.keys}
        {#each info.value as row}
          <tr>
            {#each info.keys as key}
              <td>
                <svelte:self value={row[key]} />
              </td>
            {/each}
          </tr>
        {/each}
      {:else}
        {#each info.value as row}
          <tr>
            <td>
              <svelte:self value={row} />
            </td>
          </tr>
        {/each}
      {/if}
    </tbody>
  </Table>
{:else}
  <div>Unknown</div>
{/if}

// react-viewer/src/Viewer.tsx
import React from 'react';
import { Table, Container, Row, Col } from 'react-bootstrap';
import { getRenderType } from './common/meta';


export function Viewer(i: { value: unknown, maxDepth?: number }) {
    const maxDepth = i.maxDepth || 1;
    const info = getRenderType(i.value);
    return (
        <Container>
            <Row>
                <Col>
                    <Json value={{ info, maxDepth }}></Json>
                </Col>
            </Row>
        </Container>
    );
}

export function Json(i: { value: unknown }) {
    return (<pre>{JSON.stringify(i.value, null, 2)}</pre>)
}

export function SimpleObject(props: { value: object }) {
    return (
        <Table striped bordered hover size="sm">
            <thead>
                <tr>
                    <th>#</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Username</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>Mark</td>
                    <td>Otto</td>
                    <td>@mdo</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Jacob</td>
                    <td>Thornton</td>
                    <td>@fat</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td colSpan={2}>Larry the Bird</td>
                    <td>@twitter</td>
                </tr>
            </tbody>
        </Table>
    );
}
